#!/usr/bin/env python

import sys

from rover_relay_control.rover_relay_control_Plugin import RoverRelayControlPlugin
from rqt_gui.main import Main

plugin = 'rover_relay_control'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
