float32[20] joy_data

uint8 JOYSTICK_LEFT_FRONT = 0
uint8 JOYSTICK_LEFT_SIDE = 1
uint8 JOYSTICK_LEFT_PUSH = 2
uint8 JOYSTICK_RIGHT_FRONT = 3
uint8 JOYSTICK_RIGHT_SIDE = 4
uint8 JOYSTICK_RIGHT_PUSH = 5
uint8 CROSS_UP = 6
uint8 CROSS_DOWN = 7
uint8 CROSS_LEFT = 8
uint8 CROSS_RIGHT = 9
uint8 L1 = 10
uint8 L2 = 11
uint8 R1 = 12
uint8 R2 = 13
uint8 A = 14
uint8 B = 15
uint8 X = 16
uint8 Y = 17
uint8 EXT0 = 18
uint8 EXT1 = 19
uint8 EXT2 = 20

