odom_frame: odom
map_frame: map
base_link_frame: base_link
world_frame: odom

two_d_mode: true
publish_tf: true

frequency: 50
transform_time_offset: 0.05

odom0: odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

 
