nb_sensors: 5
sensor_1:
  name: imu
  sensor_id: imu
  topic: /imu/data
  max_freq: 110
  min_freq: 90

sensor_2:
  name: depth_camera
  sensor_id: depth_camera
  topic: /d435/depth/color/points
  max_freq: 8
  min_freq: 2

sensor_3:
  name: gps
  sensor_id: gps
  topic: /fix
  max_freq: 2.5
  min_freq: 0.5

sensor_4:
  name: odom
  sensor_id: odom
  topic: /odom
  max_freq: 60
  min_freq: 40

sensor_5:
  name: Base_Station_Heartbeat
  sensor_id: Heartbeat
  topic: /heartbeat
  max_freq: 25
  min_freq: 15

#sensor_6:
#  name: Color_camera
#  sensor_id: Color_camera
#  topic: /d435/color/image_raw
#  max_freq: 20
#  min_freq: 10


