#!/usr/bin/env python

import sys

# from rover_launch_control.Rover_Launch_Control_Plugin import RoverLaunchControlPlugin
from rqt_gui.main import Main
import rospy

plugin = 'rover_launch_control'

main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
