let viewer;
let currentPosition = { latitude: 45.377755, longitude: -71.924652 };
let pathEntity = null;
let waypointEntities = [];
let waypointCounter = 1;
let activeWaypoint = null;
let pathUpdateInterval = null;
let entity;
let isAddingWaypoint = false;
let cameraTracking = false;
let isTopDownView = false;
let lastHeading = 0;
let lastCameraPosition = null;
let isFacingNorth = false;
let isAdjustingCamera = false;
let northFacingTimeout = null;