#!/usr/bin/env python

import sys

from rover_arm_gui.Rover_Arm_Gui_Plugin import RoverArmGuiPlugin
from rqt_gui.main import Main

plugin = 'rover_arm_gui'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
