<?xml version="1.0" ?>
<robot name="rover" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find rover_description)/urdf/camera.urdf.xacro"/>
  <xacro:include filename="$(find rover_description)/urdf/stereo_camera.urdf.xacro"/>
  <xacro:include filename="$(find rover_description)/urdf/realsense_d435.urdf.xacro" />

  <xacro:arg name="robot_namespace" default="/" />

  <!-- TODO: adjust geometry-->
  <!-- Base size -->
  <xacro:property name="base_x_size" value="1" />
  <xacro:property name="base_y_size" value="0.625" />
  <xacro:property name="base_z_size" value="0.2" />

  <!-- Wheel mounting positions -->
  <xacro:property name="wheelbase" value="0.5" />
  <xacro:property name="track" value="${base_y_size}" />
  <xacro:property name="wheel_vertical_offset" value="-0.03" />

  <!-- Wheel properties -->
  <xacro:property name="wheel_length" value="0.125" />
  <xacro:property name="wheel_radius" value="0.2" />

  <!-- Base link -->
  <link name='base_link'>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
      </geometry>
    </collision>
  </link>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint" />

  <joint name="base_footprint_joint" type="fixed" >
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- Interial link stores the robot's inertial information -->
  <link name="inertial_link">
    <inertial>
      <mass value="20" />  <!-- TODO: adjust to our values-->
      <origin xyz="0 0 0" />
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="1" iyz="0" izz="2" />
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- IMU link -->
  <link name="imu_link"/>

  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />  <!-- TODO: adjust values -->
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>
  <gazebo reference="imu_link">
  </gazebo>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="wheel_prefix *joint_pose" >
    <link name="${wheel_prefix}_wheel_link" >
      <inertial>#
        <mass value="2" />
				<origin xyz="0 0 0" />
				<inertia  ixx="0.02" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.02" />
      </inertial>
      <visual>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</visual>
      <collision>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</collision>
    </link>

    <gazebo reference="${wheel_prefix}_wheel_link">
			<mu1 value="1.0"/>
			<mu2 value="1.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
		</gazebo>

		<joint name="${wheel_prefix}_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="${wheel_prefix}_wheel_link"/>
			<xacro:insert_block name="joint_pose"/>
			<axis xyz="0 1 0" rpy="0 0 0" />
		</joint>

    <transmission name="${wheel_prefix}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="${wheel_prefix}_wheel_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
			<joint name="${wheel_prefix}_wheel">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</joint>
		</transmission>
  </xacro:macro>

  <!-- Calls to wheel macro -->
  <xacro:wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2 + wheel_length/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2 - wheel_length/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2  + wheel_length/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2  - wheel_length/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

  <!-- Camera -->
  <xacro:camera_sensor name="camera1" parent="base_link" hfov="1.3962634" image_width="800" image_height="600"  >
    <origin xyz="0 0 0.5" rpy="0 0 0" />
  </xacro:camera_sensor>

  <!-- Stereo camera -->
  <!--<xacro:stereo_camera_sensor name="stereo_camera" parent="base_link" hfov="1.3962634" image_width="800" image_height="600" camera_distance="0.1" >
    <origin xyz="${base_x_size/2} 0 0" rpy="0 0 0" />
  </xacro:stereo_camera_sensor>-->

  <!-- Intel RealSense d435 -->
  <xacro:realsense_d435_sensor name="d435" parent="base_link" >
    <origin xyz="${base_x_size/2} 0 ${base_z_size}" rpy="0 0 0" />
  </xacro:realsense_d435_sensor>

  <!-- gazebo plugins -->
  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>50.0</updateRate>
      <robotNamespace></robotNamespace>
      <leftFrontJoint>front_left_wheel</leftFrontJoint>
      <rightFrontJoint>front_right_wheel</rightFrontJoint>
      <leftRearJoint>rear_left_wheel</leftRearJoint>
      <rightRearJoint>rear_right_wheel</rightRearJoint>
      <wheelSeparation>${track}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>20</torque>
      <commandTopic>watchdog/cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_yaw>0.01</covariance_yaw>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>100.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>imu/data</topicName>
      <accelDrift>0.005 0.005 0.005</accelDrift>
      <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
      <rateDrift>0.005 0.005 0.005 </rateDrift>
      <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
      <headingDrift>0.005</headingDrift>
      <headingGaussianNoise>0.005</headingGaussianNoise>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>1</updateRate>
      <bodyName>base_link</bodyName>
      <frameId>base_link</frameId>
      <topicName>/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>45.37833584</referenceLatitude>
      <referenceLongitude>-71.9276222</referenceLongitude>
      <referenceHeading>90</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>

</robot>
