<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find rover_description)/urdf/camera.urdf.xacro"/>

  <xacro:macro name="stereo_camera_sensor" params="name parent hfov image_width image_height camera_distance *origin" >

    <xacro:property name="frame_thickness" value="0.01" />

    <link name="${name}_frame" >
      <collision>
        <origin xyz="${frame_thickness} 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${frame_thickness} ${camera_distance+0.08} 0.05"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="${frame_thickness} 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${frame_thickness} ${camera_distance+0.08} 0.05"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="0.0001" />
        <origin xyz="${frame_thickness} 0 0" rpy="0 0 ${pi}"/>
        <inertia ixx="0.0000001" ixy="0" ixz="0" iyy="0.0000001" iyz="0" izz="0.0000001" />
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <axis xyz="0 1 0" />
        <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}_frame"/>
    </joint>

    <link name="${name}_optical_frame" />

    <joint name="${name}_optical_joint" type="fixed">
      <axis xyz="0 1 0" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
      <parent link="${name}_frame"/>
      <child link="${name}_optical_frame"/>
    </joint>

    <gazebo reference="${name}_frame">
      <sensor type="multicamera" name="${name}">
        <update_rate>30.0</update_rate>
        <camera name="left">
          <pose>${frame_thickness} ${camera_distance/2} 0 0 0 0</pose>
          <horizontal_fov>${hfov}</horizontal_fov>
          <image>
            <width>${image_width}</width>
            <height>${image_height}</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <camera name="right">
          <pose>${frame_thickness} ${-camera_distance/2} 0 0 0 0</pose>
          <horizontal_fov>${hfov}</horizontal_fov>
          <image>
            <width>${image_width}</width>
            <height>${image_height}</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>5.0</updateRate>
          <cameraName>${name}</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${name}_optical_frame</frameName>
          <hackBaseline>${camera_distance}</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>