#!/usr/bin/env python

import sys

from rover_cam_control.rover_cam_control_plugin import RoverCamControlPlugin
from rqt_gui.main import Main

plugin = 'rover_cam_control_plugin'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
