#!/usr/bin/env python

import sys

from rover_base.rover_base_plugin import RoverBasePlugin
from rqt_gui.main import Main

plugin = 'rover_base_plugin'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
