#!/usr/bin/env python

import sys

from rover_gui.rover_gui_plugin import RoverGuiPlugin
from rqt_gui.main import Main

plugin = 'rover_gui_plugin'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
