global_frame: odom
rolling_window: true
track_unknown_space: true

width: 15
height: 15

plugins:
  - {name: obstacle_layer,            type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}
