name: Build ROS2 Workspace

on:
  pull_request:
    branches:
      - release/**
  push:
    branches:
      - release/**

jobs:
  humble-build:
    runs-on: ubuntu-22.04

    container:
      image: osrf/ros:humble-desktop

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          echo "\e[0;34m=== Downloading and installing packages dependencies ... ===\e[0m"
          chmod +x scripts/provision.sh
          scripts/provision.sh
          echo -e "\e[0;32m[OK] Dependencies installed successfully\e[0m"
        
      - name: Building rover packages
        run: |
          echo "\e[0;34m=== Sourcing for build ... ===\e[0m"
          source /opt/ros/humble/setup.bash
          echo -e "\e[0;32m[OK]\e[0m"
          
          echo "\e[0;34m=== Building ROS2 Packages ... ===\e[0m"
          if colcon build --event-handlers console_cohesion+; then
            echo "Build succeeded!"
            echo -e "\e[0;32m[SUCCESS]\e[0m"
          else
            echo -e "\e[0;31m[FAILED] Building step triggered warnings or errors\e[0m"
            exit 1  # Exit with status 1 if build fails
          fi
