# Camera parameters
string camera_ip
int32 camera_port
string camera_username
string camera_password
int32 camera_timeout

# Camera setting to change
string parameter_name   
string parameter_type   
string string_value 
int32 int_value         
bool bool_value       
bool bool_value2        
---
bool success
string message      