footprint: [[0.18, 0.25], [-0.18, 0.25], [-0.18, -0.25], [0.18, -0.25]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
#static:
#    map_topic: /map
#    subscribe_to_updates: true

obstacle_layer:
    observation_sources: rgbd
    rgbd: {data_type: PointCloud2, topic: /d435/depth/color/points, marking: true, clearing: true, sensor_frame: d435_depth_optical_frame, max_obstacle_height: 2.0, min_obstacle_height: 0.2} 

inflation_layer:
    inflation_radius: 1.0
